import os

print(dir(os))
print(os.getcwd())
# os.chdir("c://")
# print(os.getcwd())
print(os.listdir("E://2.DESIGNED DRAWINGS PROGRAMS"))
# os.makedirs("mydir1/mydir2")
# os.mkdir("osmodule")
# os.rename("rahul.txt","harry.txt")
# os.rename("harry.txt","rahul.txt")
print(os.environ.get("path"))
print(os.path.join("c:/","//harry.txt"))
print(os.path.exists("c://Program Files"))
print(os.path.isdir("c://Program Files"))
print(os.path.isfile("c://Program Files"))
