import re
mytext="the rain in spain"
mytext2="hello newawap rat 11.45 pm"



x=re.findall("ai",mytext)
print(x)
x=re.findall("aiz",mytext)
print(x)
x=re.search("ai",mytext)
print(x)
print(x.span())
print(x.start())
print(x.end())
print(x.string)
print(x.group())
x=re.split(" ",mytext,2)
print(x)
print(r"\n")
x=re.sub("ai","zp",mytext,1)
print(x)
x=re.match("the",mytext)
print(x)
x=re.fullmatch("the rain in spain",mytext)
print(x)
x=re.finditer("ai",mytext)
# print(x)
for element in x:
    print(element)



x=re.findall(r"he..o",mytext2)
print(x)
x=re.findall(r"^hello",mytext2)
print(x)
x=re.findall(r"pm$",mytext2)
print(x)
x=re.findall(r"he.*o",mytext2)
print(x)
x=re.findall(r"he.+o",mytext2)
print(x)
x=re.findall(r"helll?o",mytext2)
print(x)
x=re.findall(r"hel{2}o",mytext2)
print(x)
x=re.findall(r"hello|bye",mytext2)
print(x)
x=re.finditer(r"ne(wa){2}p",mytext2)
for element in x:
    print(element)



x=re.findall(r"[a,r,n]",mytext2)
print(x)
x=re.findall(r"[a-n]",mytext2)
print(x)
x=re.findall(r"[0,4,5]",mytext2)
print(x)
x=re.findall(r"[0-9]",mytext2)
print(x)
x=re.findall(r"[a-zA-Z]",mytext2)
print(x)
x=re.findall(r"[^w at1]",mytext2)
print(x)



x=re.findall(r"\Ahello",mytext2)
print(x)
x=re.findall(r"pm\Z",mytext2)
print(x)
x=re.findall(r"\bra",mytext2)
print(x)
x=re.findall(r"at\b",mytext2)
print(x)
x=re.findall(r"\Bain",mytext)
print(x)
x=re.findall(r"ain\B",mytext)
print(x)
x=re.findall(r"\d",mytext2)
print(x)
x=re.findall(r"\D",mytext2)
print(x)
x=re.findall(r"\s",mytext2)
print(x)
x=re.findall(r"\S",mytext2)
print(x)
x=re.findall(r"\w",mytext2)
print(x)
x=re.findall(r"\W",mytext2)
print(x)
