name="rahul is a badis boy and SHYAN IS A GOOD BOY"
print(len(name))
print(name[4])
print(name)
print(name[::-1])
print(name[::-2])
print(name.isalnum())
print(name.endswith("s boy"))
print(name.count("a"))
print(name.capitalize())
print(name.lower())
print(name.upper())
print(name.title())
print(name.swapcase())
print(name.find("is"))
print(name.rfind("is"))
print(name.replace("is","are"))